baseURL: 'https://keertana.me/'
languageCode: 'en-us'
title: 'Keertana Gollahalli'
theme: 'Indigo'

googleAnalytics: 'G-VXFCTM73V4'
disqusShortname: 'keertana'
pygmentsCodeFences: true
enableRobotsTXT: true
enableEmoji: true

uhugo:
  name: "cloudflare"
  project: "keertana-gollahalli-com"
  email_address: "env:cloudflare_email"
  account_id: "env:cloudflare_account_id"
  api_key: "env:cloudflare_key"

markup:
  highlight:
    style: 'dracula'

outputFormats:
  searchindex:
    mediaType: 'application/json'
    baseName: 'searchindex'
    isPlainText: true

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'AMP'
    - 'searchindex'
  page:
    - 'HTML'
    - 'RSS'
    - 'AMP'
  section:
    - 'HTML'
    - 'RSS'
    - 'AMP'

params:
  logo: '/img/logo.svg'
  title: 'Dr Keertana Tipparaju Gollahalli'
  images:
    - 'img/keertana-photo.jpg'
  linkedin: 'https://www.linkedin.com/in/drkeertana/'
  photo: '/img/keertana-photo.jpg'
  email: 'keertana@gollahalli.com'
  description: 'Hi! My name is Keertana, and I am just your friendly neighbourhood Dentist (or maybe slightly far away, at the end of the world)'
  cloudflareInsight: '107cda45c47644b4bf2d025b603af92d'
  year: '2025'
  author:
    city: 'Auckland'
    country: 'New Zealand'
    jobTitle: 'Dental Assistant'
    firstName: 'Keertana'
    lastName: 'Gollahalli'
    prefix: 'Dr'
  seo:
    noIndexTags: true
    noIndexCategories: true
